import { baseConfig, baseJsConfig, reactConfig } from '@mheob/oxlint-config';
import { defineConfig } from 'oxlint';

// `storybookConfig` and `tailwindcssConfig` get added once apps/web has Storybook
// stories and Tailwind classNames to lint, respectively — each needs its own
// ESLint-plugin devDependency that nothing in the repo uses yet.
export default defineConfig({
	extends: [baseConfig, baseJsConfig, reactConfig],
	ignorePatterns: [
		// Generated from apps/api/openapi.json by @hey-api/openapi-ts, including the
		// vendored request runtime. Linting it would report on the generator's
		// output style, which nobody here can act on without editing files that are
		// overwritten on every regeneration.
		'packages/api-client/src/generated/**',
		// Generated by TanStack Router (`tsr generate` / the Vite plugin) from the
		// files under src/routes/. Its own header says not to edit or lint it.
		'apps/web/src/routeTree.gen.ts',
	],
});
