/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedTeamsNewRouteImport } from './routes/_authed/teams.new'
import { Route as AuthedTeamsTeamSlugDomainsRouteImport } from './routes/_authed/teams.$teamSlug.domains'
import { Route as AuthedTeamsTeamSlugLinksIndexRouteImport } from './routes/_authed/teams.$teamSlug.links.index'
import { Route as AuthedTeamsTeamSlugLinksLinkIdRouteImport } from './routes/_authed/teams.$teamSlug.links.$linkId'
import { Route as AuthedTeamsTeamSlugLinksNewRouteImport } from './routes/_authed/teams.$teamSlug.links.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeamsNewRoute = AuthedTeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamsTeamSlugDomainsRoute =
  AuthedTeamsTeamSlugDomainsRouteImport.update({
    id: '/teams/$teamSlug/domains',
    path: '/teams/$teamSlug/domains',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTeamsTeamSlugLinksIndexRoute =
  AuthedTeamsTeamSlugLinksIndexRouteImport.update({
    id: '/teams/$teamSlug/links/',
    path: '/teams/$teamSlug/links/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTeamsTeamSlugLinksLinkIdRoute =
  AuthedTeamsTeamSlugLinksLinkIdRouteImport.update({
    id: '/teams/$teamSlug/links/$linkId',
    path: '/teams/$teamSlug/links/$linkId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTeamsTeamSlugLinksNewRoute =
  AuthedTeamsTeamSlugLinksNewRouteImport.update({
    id: '/teams/$teamSlug/links/new',
    path: '/teams/$teamSlug/links/new',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/new': typeof AuthedTeamsNewRoute
  '/teams/$teamSlug/domains': typeof AuthedTeamsTeamSlugDomainsRoute
  '/teams/$teamSlug/links/$linkId': typeof AuthedTeamsTeamSlugLinksLinkIdRoute
  '/teams/$teamSlug/links/new': typeof AuthedTeamsTeamSlugLinksNewRoute
  '/teams/$teamSlug/links/': typeof AuthedTeamsTeamSlugLinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/new': typeof AuthedTeamsNewRoute
  '/teams/$teamSlug/domains': typeof AuthedTeamsTeamSlugDomainsRoute
  '/teams/$teamSlug/links/$linkId': typeof AuthedTeamsTeamSlugLinksLinkIdRoute
  '/teams/$teamSlug/links/new': typeof AuthedTeamsTeamSlugLinksNewRoute
  '/teams/$teamSlug/links': typeof AuthedTeamsTeamSlugLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/teams/new': typeof AuthedTeamsNewRoute
  '/_authed/teams/$teamSlug/domains': typeof AuthedTeamsTeamSlugDomainsRoute
  '/_authed/teams/$teamSlug/links/$linkId': typeof AuthedTeamsTeamSlugLinksLinkIdRoute
  '/_authed/teams/$teamSlug/links/new': typeof AuthedTeamsTeamSlugLinksNewRoute
  '/_authed/teams/$teamSlug/links/': typeof AuthedTeamsTeamSlugLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/teams/new'
    | '/teams/$teamSlug/domains'
    | '/teams/$teamSlug/links/$linkId'
    | '/teams/$teamSlug/links/new'
    | '/teams/$teamSlug/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/teams/new'
    | '/teams/$teamSlug/domains'
    | '/teams/$teamSlug/links/$linkId'
    | '/teams/$teamSlug/links/new'
    | '/teams/$teamSlug/links'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/auth/callback'
    | '/_authed/teams/new'
    | '/_authed/teams/$teamSlug/domains'
    | '/_authed/teams/$teamSlug/links/$linkId'
    | '/_authed/teams/$teamSlug/links/new'
    | '/_authed/teams/$teamSlug/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teams/new': {
      id: '/_authed/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AuthedTeamsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamSlug/domains': {
      id: '/_authed/teams/$teamSlug/domains'
      path: '/teams/$teamSlug/domains'
      fullPath: '/teams/$teamSlug/domains'
      preLoaderRoute: typeof AuthedTeamsTeamSlugDomainsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamSlug/links/': {
      id: '/_authed/teams/$teamSlug/links/'
      path: '/teams/$teamSlug/links'
      fullPath: '/teams/$teamSlug/links/'
      preLoaderRoute: typeof AuthedTeamsTeamSlugLinksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamSlug/links/$linkId': {
      id: '/_authed/teams/$teamSlug/links/$linkId'
      path: '/teams/$teamSlug/links/$linkId'
      fullPath: '/teams/$teamSlug/links/$linkId'
      preLoaderRoute: typeof AuthedTeamsTeamSlugLinksLinkIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamSlug/links/new': {
      id: '/_authed/teams/$teamSlug/links/new'
      path: '/teams/$teamSlug/links/new'
      fullPath: '/teams/$teamSlug/links/new'
      preLoaderRoute: typeof AuthedTeamsTeamSlugLinksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedTeamsNewRoute: typeof AuthedTeamsNewRoute
  AuthedTeamsTeamSlugDomainsRoute: typeof AuthedTeamsTeamSlugDomainsRoute
  AuthedTeamsTeamSlugLinksLinkIdRoute: typeof AuthedTeamsTeamSlugLinksLinkIdRoute
  AuthedTeamsTeamSlugLinksNewRoute: typeof AuthedTeamsTeamSlugLinksNewRoute
  AuthedTeamsTeamSlugLinksIndexRoute: typeof AuthedTeamsTeamSlugLinksIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTeamsNewRoute: AuthedTeamsNewRoute,
  AuthedTeamsTeamSlugDomainsRoute: AuthedTeamsTeamSlugDomainsRoute,
  AuthedTeamsTeamSlugLinksLinkIdRoute: AuthedTeamsTeamSlugLinksLinkIdRoute,
  AuthedTeamsTeamSlugLinksNewRoute: AuthedTeamsTeamSlugLinksNewRoute,
  AuthedTeamsTeamSlugLinksIndexRoute: AuthedTeamsTeamSlugLinksIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
