/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedTeamsTeamIdLinksIndexRouteImport } from './routes/_authed/teams.$teamId.links.index'
import { Route as AuthedTeamsTeamIdLinksLinkIdRouteImport } from './routes/_authed/teams.$teamId.links.$linkId'
import { Route as AuthedTeamsTeamIdLinksNewRouteImport } from './routes/_authed/teams.$teamId.links.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeamsTeamIdLinksIndexRoute =
  AuthedTeamsTeamIdLinksIndexRouteImport.update({
    id: '/teams/$teamId/links/',
    path: '/teams/$teamId/links/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTeamsTeamIdLinksLinkIdRoute =
  AuthedTeamsTeamIdLinksLinkIdRouteImport.update({
    id: '/teams/$teamId/links/$linkId',
    path: '/teams/$teamId/links/$linkId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTeamsTeamIdLinksNewRoute =
  AuthedTeamsTeamIdLinksNewRouteImport.update({
    id: '/teams/$teamId/links/new',
    path: '/teams/$teamId/links/new',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$teamId/links/$linkId': typeof AuthedTeamsTeamIdLinksLinkIdRoute
  '/teams/$teamId/links/new': typeof AuthedTeamsTeamIdLinksNewRoute
  '/teams/$teamId/links/': typeof AuthedTeamsTeamIdLinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$teamId/links/$linkId': typeof AuthedTeamsTeamIdLinksLinkIdRoute
  '/teams/$teamId/links/new': typeof AuthedTeamsTeamIdLinksNewRoute
  '/teams/$teamId/links': typeof AuthedTeamsTeamIdLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/teams/$teamId/links/$linkId': typeof AuthedTeamsTeamIdLinksLinkIdRoute
  '/_authed/teams/$teamId/links/new': typeof AuthedTeamsTeamIdLinksNewRoute
  '/_authed/teams/$teamId/links/': typeof AuthedTeamsTeamIdLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/teams/$teamId/links/$linkId'
    | '/teams/$teamId/links/new'
    | '/teams/$teamId/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/teams/$teamId/links/$linkId'
    | '/teams/$teamId/links/new'
    | '/teams/$teamId/links'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/auth/callback'
    | '/_authed/teams/$teamId/links/$linkId'
    | '/_authed/teams/$teamId/links/new'
    | '/_authed/teams/$teamId/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teams/$teamId/links/': {
      id: '/_authed/teams/$teamId/links/'
      path: '/teams/$teamId/links'
      fullPath: '/teams/$teamId/links/'
      preLoaderRoute: typeof AuthedTeamsTeamIdLinksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamId/links/$linkId': {
      id: '/_authed/teams/$teamId/links/$linkId'
      path: '/teams/$teamId/links/$linkId'
      fullPath: '/teams/$teamId/links/$linkId'
      preLoaderRoute: typeof AuthedTeamsTeamIdLinksLinkIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$teamId/links/new': {
      id: '/_authed/teams/$teamId/links/new'
      path: '/teams/$teamId/links/new'
      fullPath: '/teams/$teamId/links/new'
      preLoaderRoute: typeof AuthedTeamsTeamIdLinksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedTeamsTeamIdLinksLinkIdRoute: typeof AuthedTeamsTeamIdLinksLinkIdRoute
  AuthedTeamsTeamIdLinksNewRoute: typeof AuthedTeamsTeamIdLinksNewRoute
  AuthedTeamsTeamIdLinksIndexRoute: typeof AuthedTeamsTeamIdLinksIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTeamsTeamIdLinksLinkIdRoute: AuthedTeamsTeamIdLinksLinkIdRoute,
  AuthedTeamsTeamIdLinksNewRoute: AuthedTeamsTeamIdLinksNewRoute,
  AuthedTeamsTeamIdLinksIndexRoute: AuthedTeamsTeamIdLinksIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
