// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuditLog = `-- name: CountAuditLog :one

select count(*)
from audit_log
where team_id = $1::uuid
  and ($2::text is null or entity_type = $2::text)
  and ($3::text is null or action = $3::text)
  and ($4::uuid is null or actor_user_id = $4::uuid)
  and ($5::timestamptz is null or created_at >= $5::timestamptz)
  and ($6::timestamptz is null or created_at <= $6::timestamptz)
`

type CountAuditLogParams struct {
	TeamID      uuid.UUID
	EntityType  *string
	Action      *string
	ActorUserID *uuid.UUID
	From        *time.Time
	To          *time.Time
}

// Fallback for a page past the end; see CountTeamsForUser in team.sql. Mirrors
// ListAuditLog's filters exactly so the recovered total matches the same set
// of rows the paginated query would have counted.
func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog,
		arg.TeamID,
		arg.EntityType,
		arg.Action,
		arg.ActorUserID,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredAuditLog = `-- name: DeleteExpiredAuditLog :execrows

delete from audit_log
where created_at < $1::timestamptz
`

// Retention. Audit entries are kept for api.AuditRetentionYears (two years)
// and POST /internal/retention deletes everything older, after the click
// rollup's own delete.
//
// :execrows for the reason DeleteExpiredClickStats gives: the row count is the
// only evidence the job did anything, and for the first two years nothing is
// old enough to delete, so "0 rows" is the correct answer.
//
// The floor is a parameter, never a literal. GET /v1/teams/{team_id}/audit-log
// serves created_at >= the same instant, computed by api.auditRetentionFloor;
// an interval written here as well would be a second definition of one
// boundary, and the two drifting apart would either show entries the policy
// says are gone or hide entries the endpoint still offers.
//
// No team_id, deliberately — the one documented exception to golden rule 4,
// for the same reason as DeleteExpiredClickStats: a nightly job acts for the
// instance, not for a caller, and the retention period is the same for every
// Verein. Scoping it to a team would make the promise depend on who called.
func (q *Queries) DeleteExpiredAuditLog(ctx context.Context, oldestKept time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuditLog, oldestKept)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec

insert into audit_log (team_id, actor_user_id, action, entity_type, entity_id, metadata)
values ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	TeamID      *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Metadata    []byte
}

// Audit log. Writes always share the transaction of the mutation they record;
// see db.InTx.
// No cast on metadata: sqlc's default pgx/v5 mapping generates jsonb as
// []byte, and Postgres has no cast from text to jsonb, so an explicit
// ::text or ::jsonb cast here would break the insert rather than help it.
// Leave this parameter uncast so Postgres keeps inferring it as jsonb from
// the insert context, and pgx.QueryExecModeCacheDescribe (cmd/api/main.go)
// keeps a real, server-described OID for it even through Supavisor's
// transaction pooler, so a plain []byte argument encodes correctly.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TeamID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
select id, team_id, actor_user_id, action, entity_type, entity_id, metadata, created_at,
       count(*) over () as total_count
from audit_log
where team_id = $1::uuid
  and ($2::text is null or entity_type = $2::text)
  and ($3::text is null or action = $3::text)
  and ($4::uuid is null or actor_user_id = $4::uuid)
  and ($5::timestamptz is null or created_at >= $5::timestamptz)
  and ($6::timestamptz is null or created_at <= $6::timestamptz)
order by created_at desc, id desc
limit $8 offset $7
`

type ListAuditLogParams struct {
	TeamID       uuid.UUID
	EntityType   *string
	Action       *string
	ActorUserID  *uuid.UUID
	From         *time.Time
	To           *time.Time
	ResultOffset int32
	ResultLimit  int32
}

type ListAuditLogRow struct {
	ID          int64
	TeamID      *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Metadata    []byte
	CreatedAt   time.Time
	TotalCount  int64
}

// The explicit ::uuid cast on team_id keeps the required (non-nullable)
// caller-provided parameter typed as uuid.UUID rather than *uuid.UUID, even
// though the audit_log.team_id column itself is nullable (see the migration:
// "on delete set null"). Without the cast sqlc infers the param's
// nullability from the column and generates a pointer.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.TeamID,
		arg.EntityType,
		arg.Action,
		arg.ActorUserID,
		arg.From,
		arg.To,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
