// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

insert into audit_log (team_id, actor_user_id, action, entity_type, entity_id, metadata)
values ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	TeamID      *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Metadata    []byte
}

// Audit log. Writes always share the transaction of the mutation they record;
// see db.InTx.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TeamID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
select id, team_id, actor_user_id, action, entity_type, entity_id, metadata, created_at,
       count(*) over () as total_count
from audit_log
where team_id = $1::uuid
  and ($2::text is null or entity_type = $2::text)
  and ($3::text is null or action = $3::text)
  and ($4::uuid is null or actor_user_id = $4::uuid)
  and ($5::timestamptz is null or created_at >= $5::timestamptz)
  and ($6::timestamptz is null or created_at <= $6::timestamptz)
order by created_at desc, id desc
limit $8 offset $7
`

type ListAuditLogParams struct {
	TeamID       uuid.UUID
	EntityType   *string
	Action       *string
	ActorUserID  *uuid.UUID
	From         *time.Time
	To           *time.Time
	ResultOffset int32
	ResultLimit  int32
}

type ListAuditLogRow struct {
	ID          int64
	TeamID      *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Metadata    []byte
	CreatedAt   time.Time
	TotalCount  int64
}

// The explicit ::uuid cast on team_id keeps the required (non-nullable)
// caller-provided parameter typed as uuid.UUID rather than *uuid.UUID, even
// though the audit_log.team_id column itself is nullable (see the migration:
// "on delete set null"). Without the cast sqlc infers the param's
// nullability from the column and generates a pointer.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.TeamID,
		arg.EntityType,
		arg.Action,
		arg.ActorUserID,
		arg.From,
		arg.To,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
