// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertClickStats = `-- name: UpsertClickStats :batchexec

insert into link_click_stats
  (link_id, bucket_start, dimension_type, dimension_value, clicks, unique_visitors)
values ($1, $2, $3, $4, $5, $6)
on conflict (link_id, bucket_start, dimension_type, dimension_value)
do update set
  clicks = link_click_stats.clicks + excluded.clicks,
  unique_visitors = link_click_stats.unique_visitors + excluded.unique_visitors
`

type UpsertClickStatsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertClickStatsParams struct {
	LinkID         uuid.UUID
	BucketStart    time.Time
	DimensionType  string
	DimensionValue *string
	Clicks         int64
	UniqueVisitors int64
}

// Batched rollup upsert. The unique constraint is NULLS NOT DISTINCT, which
// is what lets the dimension_type = 'total' row (dimension_value is null)
// increment rather than duplicate.
func (q *Queries) UpsertClickStats(ctx context.Context, arg []UpsertClickStatsParams) *UpsertClickStatsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LinkID,
			a.BucketStart,
			a.DimensionType,
			a.DimensionValue,
			a.Clicks,
			a.UniqueVisitors,
		}
		batch.Queue(upsertClickStats, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertClickStatsBatchResults{br, len(arg), false}
}

func (b *UpsertClickStatsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertClickStatsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
