// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folder.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFoldersForTeam = `-- name: CountFoldersForTeam :one

select count(*) from folder where team_id = $1
`

// CountFoldersForTeam serves two callers: the pagination total when the page
// is past the end and the window function returned no rows, and the per-team
// cap check before an insert.
func (q *Queries) CountFoldersForTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersForTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLinksInFolder = `-- name: CountLinksInFolder :one

select count(*) from link where folder_id = $1 and team_id = $2
`

type CountLinksInFolderParams struct {
	FolderID *uuid.UUID
	TeamID   uuid.UUID
}

// CountLinksInFolder is read before a delete, for the audit metadata. It is a
// separate statement rather than a CTE beside the delete so that the number
// reported is unambiguously the pre-delete count.
func (q *Queries) CountLinksInFolder(ctx context.Context, arg CountLinksInFolderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksInFolder, arg.FolderID, arg.TeamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
insert into folder (team_id, name)
values ($1, $2)
returning id, team_id, name, created_at
`

type CreateFolderParams struct {
	TeamID uuid.UUID
	Name   string
}

type CreateFolderRow struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (CreateFolderRow, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.TeamID, arg.Name)
	var i CreateFolderRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :one

delete from folder
where id = $1 and team_id = $2
returning id
`

type DeleteFolderParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

// DeleteFolder returns the id so the handler can tell "deleted" from "no such
// folder in this team" without a second round trip. Links in the folder are
// unfiled by the on delete set null foreign key, not by application code.
func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteFolder, arg.ID, arg.TeamID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFolderInTeam = `-- name: GetFolderInTeam :one

select id, name
from folder
where team_id = $1 and id = $2
`

type GetFolderInTeamParams struct {
	TeamID uuid.UUID
	ID     uuid.UUID
}

type GetFolderInTeamRow struct {
	ID   uuid.UUID
	Name string
}

// GetFolderInTeam validates a folder_id supplied in a link's request body. The
// team_id comes from the authorization scope, never from the request, so a
// folder belonging to another team simply returns no row.
func (q *Queries) GetFolderInTeam(ctx context.Context, arg GetFolderInTeamParams) (GetFolderInTeamRow, error) {
	row := q.db.QueryRow(ctx, getFolderInTeam, arg.TeamID, arg.ID)
	var i GetFolderInTeamRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getFolderScope = `-- name: GetFolderScope :one


select id, team_id
from folder
where id = $1
`

type GetFolderScopeRow struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

// Folder CRUD. There is no RLS: every query here except GetFolderScope filters
// by team_id, because Postgres enforces nothing about tenancy.
//
// parent_folder_id is never written. Folders are flat in this iteration and the
// column is left for a later plan; no statement below names it, so the column
// default applies and it stays NULL.
// GetFolderScope is the one deliberate exception to the team_id rule. It is
// what the FolderEditorScope resolver calls to *discover* which team a folder
// belongs to, so it cannot filter by the answer. Everything the handler does
// afterwards is filtered by the team_id this returns.
func (q *Queries) GetFolderScope(ctx context.Context, id uuid.UUID) (GetFolderScopeRow, error) {
	row := q.db.QueryRow(ctx, getFolderScope, id)
	var i GetFolderScopeRow
	err := row.Scan(&i.ID, &i.TeamID)
	return i, err
}

const listFoldersForTeam = `-- name: ListFoldersForTeam :many

select id, team_id, name, created_at, count(*) over () as total_count
from folder
where team_id = $1
order by name, id
limit $2 offset $3
`

type ListFoldersForTeamParams struct {
	TeamID uuid.UUID
	Limit  int32
	Offset int32
}

type ListFoldersForTeamRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	Name       string
	CreatedAt  time.Time
	TotalCount int64
}

// Paginated. count(*) over () gives the total in the same scan, so the list and
// its total_count cannot disagree the way two separate queries can. Ordered by
// name because a folder list is something a human reads alphabetically, then
// by id: unlike tag, folder has no unique constraint on (team_id, name), so
// two folders sharing a name would otherwise tie-break non-deterministically —
// a client paging through the list could see one twice and miss another.
func (q *Queries) ListFoldersForTeam(ctx context.Context, arg ListFoldersForTeamParams) ([]ListFoldersForTeamRow, error) {
	rows, err := q.db.Query(ctx, listFoldersForTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoldersForTeamRow{}
	for rows.Next() {
		var i ListFoldersForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :one
update folder
set name = $3
where id = $1 and team_id = $2
returning id, team_id, name, created_at
`

type UpdateFolderParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
	Name   string
}

type UpdateFolderRow struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (UpdateFolderRow, error) {
	row := q.db.QueryRow(ctx, updateFolder, arg.ID, arg.TeamID, arg.Name)
	var i UpdateFolderRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
