// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_crud.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinksForTeam = `-- name: CountLinksForTeam :one

select count(*)
from link l
where l.team_id = $1
  and ($2::text is null or l.state = $2::text)
  and ($3::uuid is null or l.domain_id = $3::uuid)
  and ($4::text is null
       or l.slug ilike '%' || $4::text || '%'
       or l.destination_url ilike '%' || $4::text || '%')
`

type CountLinksForTeamParams struct {
	TeamID   uuid.UUID
	State    *string
	DomainID *uuid.UUID
	Q        *string
}

// CountLinksForTeam repeats the filters because the page-past-the-end fallback
// needs a total when the windowed count returned no rows to carry it.
func (q *Queries) CountLinksForTeam(ctx context.Context, arg CountLinksForTeamParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksForTeam,
		arg.TeamID,
		arg.State,
		arg.DomainID,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
with inserted as (
  insert into link (domain_id, team_id, slug, destination_url, redirect_type,
                    expires_at, analytics_enabled, created_by, folder_id)
  values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
  returning id, domain_id, team_id, slug, destination_url, redirect_type, state, folder_id, expires_at, password_hash, analytics_enabled, created_by, created_at, updated_at, qr_size, qr_error_correction, qr_margin, qr_logo_url, qr_fg_color, qr_bg_color
)
select i.id, i.domain_id, i.team_id, d.hostname, i.slug, i.destination_url,
       i.redirect_type, i.state, i.expires_at,
       (i.password_hash is not null)::boolean as has_password,
       i.analytics_enabled, i.folder_id, i.created_by, i.created_at, i.updated_at
from inserted i
join domain d on d.id = i.domain_id
`

type CreateLinkParams struct {
	DomainID         uuid.UUID
	TeamID           uuid.UUID
	Slug             string
	DestinationURL   string
	RedirectType     int16
	ExpiresAt        *time.Time
	AnalyticsEnabled bool
	CreatedBy        uuid.UUID
	FolderID         *uuid.UUID
}

type CreateLinkRow struct {
	ID               uuid.UUID
	DomainID         uuid.UUID
	TeamID           uuid.UUID
	Hostname         string
	Slug             string
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	HasPassword      bool
	AnalyticsEnabled bool
	FolderID         *uuid.UUID
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.DomainID,
		arg.TeamID,
		arg.Slug,
		arg.DestinationURL,
		arg.RedirectType,
		arg.ExpiresAt,
		arg.AnalyticsEnabled,
		arg.CreatedBy,
		arg.FolderID,
	)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.TeamID,
		&i.Hostname,
		&i.Slug,
		&i.DestinationURL,
		&i.RedirectType,
		&i.State,
		&i.ExpiresAt,
		&i.HasPassword,
		&i.AnalyticsEnabled,
		&i.FolderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
delete from link where id = $1 and team_id = $2
`

type DeleteLinkParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLinkForAPI = `-- name: GetLinkForAPI :one
select l.id, l.domain_id, l.team_id, d.hostname, l.slug, l.destination_url,
       l.redirect_type, l.state, l.expires_at,
       (l.password_hash is not null)::boolean as has_password,
       l.analytics_enabled, l.folder_id, l.created_by, l.created_at, l.updated_at
from link l
join domain d on d.id = l.domain_id
where l.id = $1 and l.team_id = $2
`

type GetLinkForAPIParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

type GetLinkForAPIRow struct {
	ID               uuid.UUID
	DomainID         uuid.UUID
	TeamID           uuid.UUID
	Hostname         string
	Slug             string
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	HasPassword      bool
	AnalyticsEnabled bool
	FolderID         *uuid.UUID
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetLinkForAPI(ctx context.Context, arg GetLinkForAPIParams) (GetLinkForAPIRow, error) {
	row := q.db.QueryRow(ctx, getLinkForAPI, arg.ID, arg.TeamID)
	var i GetLinkForAPIRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.TeamID,
		&i.Hostname,
		&i.Slug,
		&i.DestinationURL,
		&i.RedirectType,
		&i.State,
		&i.ExpiresAt,
		&i.HasPassword,
		&i.AnalyticsEnabled,
		&i.FolderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkScope = `-- name: GetLinkScope :one


select l.id, l.team_id, l.domain_id, d.hostname, l.slug
from link l
join domain d on d.id = l.domain_id
where l.id = $1
`

type GetLinkScopeRow struct {
	ID       uuid.UUID
	TeamID   uuid.UUID
	DomainID uuid.UUID
	Hostname string
	Slug     string
}

// Link CRUD. There is no RLS: every query here except GetLinkScope filters by
// team_id, because Postgres enforces nothing about tenancy. password_hash is
// never selected — only whether one exists.
// GetLinkScope is the one deliberate exception to the team_id rule. It is what
// the LinkViewerScope/LinkEditorScope resolver calls to *discover* which team a
// link belongs to, so it cannot filter by the answer. Everything the handler
// does afterwards is filtered by the team_id this returns.
func (q *Queries) GetLinkScope(ctx context.Context, id uuid.UUID) (GetLinkScopeRow, error) {
	row := q.db.QueryRow(ctx, getLinkScope, id)
	var i GetLinkScopeRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.Hostname,
		&i.Slug,
	)
	return i, err
}

const listLinksForTeam = `-- name: ListLinksForTeam :many

select l.id, l.domain_id, l.team_id, d.hostname, l.slug, l.destination_url,
       l.redirect_type, l.state, l.expires_at,
       (l.password_hash is not null)::boolean as has_password,
       l.analytics_enabled, l.folder_id, l.created_by, l.created_at, l.updated_at,
       count(*) over () as total_count
from link l
join domain d on d.id = l.domain_id
where l.team_id = $1
  and ($2::text is null or l.state = $2::text)
  and ($3::uuid is null or l.domain_id = $3::uuid)
  and ($4::text is null
       or l.slug ilike '%' || $4::text || '%'
       or l.destination_url ilike '%' || $4::text || '%')
order by
  case when $5::boolean then l.created_at end asc,
  case when not $5::boolean then l.created_at end desc,
  l.id
limit $7 offset $6
`

type ListLinksForTeamParams struct {
	TeamID   uuid.UUID
	State    *string
	DomainID *uuid.UUID
	Q        *string
	SortAsc  bool
	Offset   int32
	Limit    int32
}

type ListLinksForTeamRow struct {
	ID               uuid.UUID
	DomainID         uuid.UUID
	TeamID           uuid.UUID
	Hostname         string
	Slug             string
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	HasPassword      bool
	AnalyticsEnabled bool
	FolderID         *uuid.UUID
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TotalCount       int64
}

// Paginated. count(*) over () gives the total in the same scan, so the list
// and its total_count cannot disagree the way two separate queries can. The
// two CASE branches in ORDER BY implement a direction switch: whichever branch
// is not selected evaluates to NULL for every row and therefore orders nothing.
// l.id is the tie-break, so paging is stable when two links share a timestamp.
func (q *Queries) ListLinksForTeam(ctx context.Context, arg ListLinksForTeamParams) ([]ListLinksForTeamRow, error) {
	rows, err := q.db.Query(ctx, listLinksForTeam,
		arg.TeamID,
		arg.State,
		arg.DomainID,
		arg.Q,
		arg.SortAsc,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksForTeamRow{}
	for rows.Next() {
		var i ListLinksForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.TeamID,
			&i.Hostname,
			&i.Slug,
			&i.DestinationURL,
			&i.RedirectType,
			&i.State,
			&i.ExpiresAt,
			&i.HasPassword,
			&i.AnalyticsEnabled,
			&i.FolderID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one

with updated as (
  update link set
    slug = $3,
    destination_url = $4,
    redirect_type = $5,
    state = $6,
    expires_at = $7,
    analytics_enabled = $8,
    folder_id = $9,
    updated_at = now()
  where link.id = $1 and link.team_id = $2
  returning id, domain_id, team_id, slug, destination_url, redirect_type, state, folder_id, expires_at, password_hash, analytics_enabled, created_by, created_at, updated_at, qr_size, qr_error_correction, qr_margin, qr_logo_url, qr_fg_color, qr_bg_color
)
select u.id, u.domain_id, u.team_id, d.hostname, u.slug, u.destination_url,
       u.redirect_type, u.state, u.expires_at,
       (u.password_hash is not null)::boolean as has_password,
       u.analytics_enabled, u.folder_id, u.created_by, u.created_at, u.updated_at
from updated u
join domain d on d.id = u.domain_id
`

type UpdateLinkParams struct {
	ID               uuid.UUID
	TeamID           uuid.UUID
	Slug             string
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	AnalyticsEnabled bool
	FolderID         *uuid.UUID
}

type UpdateLinkRow struct {
	ID               uuid.UUID
	DomainID         uuid.UUID
	TeamID           uuid.UUID
	Hostname         string
	Slug             string
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	HasPassword      bool
	AnalyticsEnabled bool
	FolderID         *uuid.UUID
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// UpdateLink writes every mutable column. The handler reads the row first,
// inside the same transaction, merges the request onto it, and passes the
// merged result here — the same read-then-write shape RenameTeam uses, and the
// reason the audit entry can list exactly which fields changed.
func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.TeamID,
		arg.Slug,
		arg.DestinationURL,
		arg.RedirectType,
		arg.State,
		arg.ExpiresAt,
		arg.AnalyticsEnabled,
		arg.FolderID,
	)
	var i UpdateLinkRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.TeamID,
		&i.Hostname,
		&i.Slug,
		&i.DestinationURL,
		&i.RedirectType,
		&i.State,
		&i.ExpiresAt,
		&i.HasPassword,
		&i.AnalyticsEnabled,
		&i.FolderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
