// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLinkForRedirect = `-- name: GetLinkForRedirect :one

select
  l.id,
  l.team_id,
  l.destination_url,
  l.redirect_type,
  l.state,
  l.expires_at,
  l.analytics_enabled,
  (l.password_hash is not null)::boolean as has_password
from link l
join domain d on d.id = l.domain_id
where d.hostname = $1
  and l.slug = $2
  and d.verification_status = 'verified'
`

type GetLinkForRedirectParams struct {
	Hostname string
	Slug     string
}

type GetLinkForRedirectRow struct {
	ID               uuid.UUID
	TeamID           uuid.UUID
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	AnalyticsEnabled bool
	HasPassword      bool
}

// Redirect-path lookup. Only verified domains resolve: an unverified domain
// must not serve links, or a team could claim a hostname it does not own.
// Note password_hash is projected as a boolean here so the hash never leaves
// the database on the hot path.
func (q *Queries) GetLinkForRedirect(ctx context.Context, arg GetLinkForRedirectParams) (GetLinkForRedirectRow, error) {
	row := q.db.QueryRow(ctx, getLinkForRedirect, arg.Hostname, arg.Slug)
	var i GetLinkForRedirectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DestinationURL,
		&i.RedirectType,
		&i.State,
		&i.ExpiresAt,
		&i.AnalyticsEnabled,
		&i.HasPassword,
	)
	return i, err
}

const getLinkForVerify = `-- name: GetLinkForVerify :one
select
  l.id,
  l.team_id,
  l.destination_url,
  l.redirect_type,
  l.state,
  l.expires_at,
  l.analytics_enabled,
  l.password_hash
from link l
join domain d on d.id = l.domain_id
where d.hostname = $1
  and l.slug = $2
  and d.verification_status = 'verified'
`

type GetLinkForVerifyParams struct {
	Hostname string
	Slug     string
}

type GetLinkForVerifyRow struct {
	ID               uuid.UUID
	TeamID           uuid.UUID
	DestinationURL   string
	RedirectType     int16
	State            string
	ExpiresAt        *time.Time
	AnalyticsEnabled bool
	PasswordHash     *string
}

func (q *Queries) GetLinkForVerify(ctx context.Context, arg GetLinkForVerifyParams) (GetLinkForVerifyRow, error) {
	row := q.db.QueryRow(ctx, getLinkForVerify, arg.Hostname, arg.Slug)
	var i GetLinkForVerifyRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DestinationURL,
		&i.RedirectType,
		&i.State,
		&i.ExpiresAt,
		&i.AnalyticsEnabled,
		&i.PasswordHash,
	)
	return i, err
}
