// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID          int64
	TeamID      *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Metadata    []byte
	CreatedAt   time.Time
}

type AuthUser struct {
	ID uuid.UUID
}

type Domain struct {
	ID                 uuid.UUID
	TeamID             uuid.UUID
	Hostname           string
	VerificationStatus string
	VercelDomainRef    *string
	CreatedAt          time.Time
	VerifiedAt         *time.Time
}

type Folder struct {
	ID             uuid.UUID
	TeamID         uuid.UUID
	ParentFolderID *uuid.UUID
	Name           string
	CreatedAt      time.Time
}

type Link struct {
	ID                uuid.UUID
	DomainID          uuid.UUID
	TeamID            uuid.UUID
	Slug              string
	DestinationURL    string
	RedirectType      int16
	State             string
	FolderID          *uuid.UUID
	ExpiresAt         *time.Time
	PasswordHash      *string
	AnalyticsEnabled  bool
	CreatedBy         uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	QrSize            *int32
	QrErrorCorrection *string
	QrMargin          *int32
	QRLogoURL         *string
	QrFgColor         *string
	QrBgColor         *string
}

type LinkClickStat struct {
	ID             int64
	LinkID         uuid.UUID
	BucketStart    time.Time
	DimensionType  string
	DimensionValue *string
	Clicks         int64
	UniqueVisitors int64
}

type LinkScanResult struct {
	ID          uuid.UUID
	LinkID      uuid.UUID
	Provider    string
	Verdict     string
	ScannedAt   time.Time
	RawResponse []byte
}

type LinkTag struct {
	LinkID uuid.UUID
	TagID  uuid.UUID
}

type Tag struct {
	ID     uuid.UUID
	TeamID uuid.UUID
	Name   string
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type TeamMember struct {
	TeamID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}
