// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countTagsForTeam = `-- name: CountTagsForTeam :one
select count(*) from tag where team_id = $1
`

func (q *Queries) CountTagsForTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsForTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
insert into tag (team_id, name)
values ($1, $2)
returning id, team_id, name
`

type CreateTagParams struct {
	TeamID uuid.UUID
	Name   string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.TeamID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.TeamID, &i.Name)
	return i, err
}

const deleteLinkTags = `-- name: DeleteLinkTags :exec


delete from link_tag where link_id = $1
`

// DeleteLinkTags and InsertLinkTags implement whole-set replacement inside the
// link write's own transaction. The delete is unconditional rather than a
// computed diff: the set is at most ten rows, and a diff would be more code
// for no measurable gain.
// DeleteLinkTags filters only by link_id because the link_tag table has no
// team_id column. Its safety is contingent on the caller: the link_id must
// already be the resolved link from a LinkEditorScope (which checked the
// caller's membership in the link's owning team) and this query runs inside
// the handler's transaction. If an invalid link_id arrives, the statement
// silently deletes nothing — the caller must validate the link exists first.
func (q *Queries) DeleteLinkTags(ctx context.Context, linkID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLinkTags, linkID)
	return err
}

const deleteTag = `-- name: DeleteTag :one

delete from tag
where id = $1 and team_id = $2
returning id, name
`

type DeleteTagParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

type DeleteTagRow struct {
	ID   uuid.UUID
	Name string
}

// DeleteTag returns the name as well as the id: the audit row records which
// tag was deleted, and returning it here costs nothing over a second lookup.
func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (DeleteTagRow, error) {
	row := q.db.QueryRow(ctx, deleteTag, arg.ID, arg.TeamID)
	var i DeleteTagRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagScope = `-- name: GetTagScope :one


select id, team_id
from tag
where id = $1
`

type GetTagScopeRow struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

// Tag CRUD and the link_tag join. There is no RLS: most queries here filter by
// team_id because Postgres enforces nothing about tenancy. Three queries do not:
// GetTagScope deliberately discovers the team (so it cannot filter by the answer),
// and DeleteLinkTags and InsertLinkTags cannot filter by team_id because the
// link_tag table has no team_id column — their safety rests entirely on the caller.
// GetTagScope discovers the owning team from a tag ID alone. It is what the
// TagEditorScope resolver calls to learn which team a tag belongs to, so it
// cannot filter by the answer and is the only query that takes only an id.
func (q *Queries) GetTagScope(ctx context.Context, id uuid.UUID) (GetTagScopeRow, error) {
	row := q.db.QueryRow(ctx, getTagScope, id)
	var i GetTagScopeRow
	err := row.Scan(&i.ID, &i.TeamID)
	return i, err
}

const insertLinkTags = `-- name: InsertLinkTags :exec

insert into link_tag (link_id, tag_id)
select $1, unnest($2::uuid[])
`

type InsertLinkTagsParams struct {
	LinkID uuid.UUID
	TagIds []uuid.UUID
}

// InsertLinkTags also cannot filter by team_id: the link_tag table stores only
// link_id and tag_id. Like DeleteLinkTags, it enforces nothing itself and relies
// on the caller. The link_id must be the resolved link (checked by LinkEditorScope),
// and every tag_id must have already been validated through ListTagsByIDs, which
// filters by the requesting team. If an invalid tag_id arrives, the foreign key
// constraint fails; if a tag from a different team arrives, the handler should
// not have passed it, but ListTagsByIDs ensures it never will.
func (q *Queries) InsertLinkTags(ctx context.Context, arg InsertLinkTagsParams) error {
	_, err := q.db.Exec(ctx, insertLinkTags, arg.LinkID, arg.TagIds)
	return err
}

const listTagsByIDs = `-- name: ListTagsByIDs :many

select id, name
from tag
where team_id = $1 and id = any($2::uuid[])
`

type ListTagsByIDsParams struct {
	TeamID uuid.UUID
	Ids    []uuid.UUID
}

type ListTagsByIDsRow struct {
	ID   uuid.UUID
	Name string
}

// ListTagsByIDs validates the tag_ids supplied in a link's request body. The
// team_id comes from the authorization scope, never from the request, so a tag
// belonging to another team simply does not come back — and the handler names
// the missing id in a 422. The message is identical for a nonexistent id and
// another team's id, so nothing leaks.
func (q *Queries) ListTagsByIDs(ctx context.Context, arg ListTagsByIDsParams) ([]ListTagsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTagsByIDs, arg.TeamID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsByIDsRow{}
	for rows.Next() {
		var i ListTagsByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForLinks = `-- name: ListTagsForLinks :many

select lt.link_id, t.id, t.name
from link_tag lt
join tag t on t.id = lt.tag_id
where lt.link_id = any($2::uuid[]) and t.team_id = $1
order by t.name
`

type ListTagsForLinksParams struct {
	TeamID  uuid.UUID
	LinkIds []uuid.UUID
}

type ListTagsForLinksRow struct {
	LinkID uuid.UUID
	ID     uuid.UUID
	Name   string
}

// ListTagsForLinks is the second query the link list runs, once per page. A
// left join onto the list query itself would be wrong rather than merely
// slower: it multiplies rows before LIMIT applies, so a page of 20 links would
// silently return fewer. The tag.team_id filter is redundant given the link
// ids are already the caller's, and it stays because a query file is read on
// its own.
func (q *Queries) ListTagsForLinks(ctx context.Context, arg ListTagsForLinksParams) ([]ListTagsForLinksRow, error) {
	rows, err := q.db.Query(ctx, listTagsForLinks, arg.TeamID, arg.LinkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForLinksRow{}
	for rows.Next() {
		var i ListTagsForLinksRow
		if err := rows.Scan(&i.LinkID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTeam = `-- name: ListTagsForTeam :many
select id, team_id, name, count(*) over () as total_count
from tag
where team_id = $1
order by name
limit $2 offset $3
`

type ListTagsForTeamParams struct {
	TeamID uuid.UUID
	Limit  int32
	Offset int32
}

type ListTagsForTeamRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	Name       string
	TotalCount int64
}

func (q *Queries) ListTagsForTeam(ctx context.Context, arg ListTagsForTeamParams) ([]ListTagsForTeamRow, error) {
	rows, err := q.db.Query(ctx, listTagsForTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForTeamRow{}
	for rows.Next() {
		var i ListTagsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
update tag
set name = $3
where id = $1 and team_id = $2
returning id, team_id, name
`

type UpdateTagParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
	Name   string
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.TeamID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.TeamID, &i.Name)
	return i, err
}
