// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
insert into team (name) values ($1)
returning id, name, created_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
delete from team_member where team_id = $1 and user_id = $2
`

type DeleteTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.UserID)
	return err
}

const getTeam = `-- name: GetTeam :one
select id, name, created_at from team where id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one

select team_id, user_id, role
from team_member
where team_id = $1 and user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

type GetTeamMembershipRow struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

// Tenancy queries. There is no RLS: every one of these filters by team_id (or
// by the caller's user_id), because Postgres enforces nothing about tenancy.
func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (GetTeamMembershipRow, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i GetTeamMembershipRow
	err := row.Scan(&i.TeamID, &i.UserID, &i.Role)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
select id from auth.users where lower(email) = lower($1) limit 1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTeamMember = `-- name: InsertTeamMember :one

insert into team_member (team_id, user_id, role) values ($1, $2, $3)
returning created_at
`

type InsertTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

// Returns created_at because POST /v1/teams/{team_id}/members echoes the
// created member back, and a fabricated timestamp would be a lie.
func (q *Queries) InsertTeamMember(ctx context.Context, arg InsertTeamMemberParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many

select tm.team_id, t.name as team_name, tm.role
from team_member tm
join team t on t.id = tm.team_id
where tm.user_id = $1
order by t.name, t.id
`

type ListMembershipsForUserRow struct {
	TeamID   uuid.UUID
	TeamName string
	Role     string
}

// Unpaginated on purpose: this drives the frontend's team switcher, and a
// person belongs to a handful of Vereine.
func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(&i.TeamID, &i.TeamName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
select tm.user_id, u.email, tm.role, tm.created_at, count(*) over () as total_count
from team_member tm
join auth.users u on u.id = tm.user_id
where tm.team_id = $1
order by u.email, tm.user_id
limit $2 offset $3
`

type ListTeamMembersParams struct {
	TeamID uuid.UUID
	Limit  int32
	Offset int32
}

type ListTeamMembersRow struct {
	UserID     uuid.UUID
	Email      *string
	Role       string
	CreatedAt  time.Time
	TotalCount int64
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many

select t.id, t.name, t.created_at, tm.role, count(*) over () as total_count
from team t
join team_member tm on tm.team_id = t.id
where tm.user_id = $1
order by t.name, t.id
limit $2 offset $3
`

type ListTeamsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type ListTeamsForUserRow struct {
	ID         uuid.UUID
	Name       string
	CreatedAt  time.Time
	Role       string
	TotalCount int64
}

// Paginated. count(*) over () gives the total in the same scan, so the list
// and its total_count cannot disagree the way two separate queries can.
func (q *Queries) ListTeamsForUser(ctx context.Context, arg ListTeamsForUserParams) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserRow{}
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeamOwners = `-- name: LockTeamOwners :many

select user_id from team_member
where team_id = $1 and role = 'owner'
for update
`

// Locks the team's owner rows for the rest of the transaction. Without this,
// two concurrent demotions both read "there are two owners" and both succeed,
// leaving the team ownerless.
func (q *Queries) LockTeamOwners(ctx context.Context, teamID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockTeamOwners, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTeam = `-- name: RenameTeam :one
update team set name = $2 where id = $1
returning id, name, created_at
`

type RenameTeamParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameTeam(ctx context.Context, arg RenameTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, renameTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :exec
update team_member set role = $3 where team_id = $1 and user_id = $2
`

type UpdateTeamMemberRoleParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateTeamMemberRole, arg.TeamID, arg.UserID, arg.Role)
	return err
}
