package main

import (
	"bytes"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestCommittedDocumentMatchesTheCode is the drift check. apps/api/openapi.json
// is committed so packages/api-client can be rebuilt without a Go toolchain,
// which means it can fall behind the code silently: an endpoint is added, the
// document is never regenerated, and the generated client is a version behind
// with nothing failing. This test is what makes that loud.
//
// It runs in the existing `go test` job, so no separate CI step is needed.
func TestCommittedDocumentMatchesTheCode(t *testing.T) {
	var generated bytes.Buffer
	require.NoError(t, run(&generated))

	committed, err := os.ReadFile("../../openapi.json")
	require.NoError(t, err, "apps/api/openapi.json is missing")

	// Compared as parsed JSON, not as bytes: the committed file is formatted by
	// oxfmt like every other file in the repo, and oxfmt and this generator
	// disagree about whitespace. That split is deliberate — `pnpm format:check`
	// owns layout, this test owns content — and it makes the check stronger,
	// since reformatting cannot mask a real change to the surface.
	require.JSONEq(t, string(committed), generated.String(),
		"apps/api/openapi.json no longer describes the code — regenerate it with:\n"+
			"  pnpm generate:api")
}

// TestTheDocumentDescribesEveryOperation guards the generator itself rather
// than the artifact. Deps is zero-valued here, so a change that made
// registration dereference a dependency would panic — and the failure would
// otherwise surface as an empty or truncated document rather than a crash.
func TestTheDocumentDescribesEveryOperation(t *testing.T) {
	var generated bytes.Buffer
	require.NoError(t, run(&generated))

	body := generated.String()
	for _, operationID := range []string{
		"get-health", "get-me",
		"create-team", "list-teams", "get-team", "update-team",
		"list-team-members", "add-team-member", "update-team-member", "remove-team-member",
		"create-link", "list-links", "get-link", "update-link", "delete-link",
		"create-folder", "list-folders", "update-folder", "delete-folder",
		"create-tag", "list-tags", "update-tag", "delete-tag",
		"list-audit-log",
	} {
		require.Contains(t, body, `"`+operationID+`"`,
			"the document is missing operation %q", operationID)
	}
}
