/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/v1/folders/{folder_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete a folder */
		delete: operations['delete-folder'];
		options?: never;
		head?: never;
		/** Rename a folder */
		patch: operations['update-folder'];
		trace?: never;
	};
	'/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Liveness probe */
		get: operations['get-health'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/links/{link_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a link */
		get: operations['get-link'];
		put?: never;
		post?: never;
		/** Delete a link */
		delete: operations['delete-link'];
		options?: never;
		head?: never;
		/** Update a link */
		patch: operations['update-link'];
		trace?: never;
	};
	'/v1/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The authenticated user and their teams */
		get: operations['get-me'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/tags/{tag_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete a tag */
		delete: operations['delete-tag'];
		options?: never;
		head?: never;
		/** Rename a tag */
		patch: operations['update-tag'];
		trace?: never;
	};
	'/v1/teams': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List the teams the caller belongs to */
		get: operations['list-teams'];
		put?: never;
		/**
		 * Create a team
		 * @description Restricted to the instance maintainers. A Verein asks the maintainer, who creates the team and invites its first owner.
		 */
		post: operations['create-team'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/teams/{team_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a team */
		get: operations['get-team'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Rename a team */
		patch: operations['update-team'];
		trace?: never;
	};
	'/v1/teams/{team_id}/audit-log': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Read a team's audit log
		 * @description Administrative history, so it is restricted to admins and owners.
		 */
		get: operations['list-audit-log'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/teams/{team_id}/folders': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List a team's folders */
		get: operations['list-folders'];
		put?: never;
		/** Create a folder */
		post: operations['create-folder'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/teams/{team_id}/links': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List a team's links */
		get: operations['list-links'];
		put?: never;
		/** Create a link */
		post: operations['create-link'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/teams/{team_id}/members': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List a team's members */
		get: operations['list-team-members'];
		put?: never;
		/**
		 * Invite or add a member
		 * @description An address without an account is invited by email; an address that already has one is added directly and sees the team on next login.
		 */
		post: operations['add-team-member'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/teams/{team_id}/members/{user_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Remove a member */
		delete: operations['remove-team-member'];
		options?: never;
		head?: never;
		/** Change a member's role */
		patch: operations['update-team-member'];
		trace?: never;
	};
	'/v1/teams/{team_id}/tags': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List a team's tags */
		get: operations['list-tags'];
		put?: never;
		/** Create a tag */
		post: operations['create-tag'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AddMemberInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/AddMemberInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * Format: email
			 * @description The person's email address.
			 */
			email: string;
			/**
			 * @description The role to grant.
			 * @enum {string}
			 */
			role: 'viewer' | 'editor' | 'admin' | 'owner';
		};
		AuditEntry: {
			action: string;
			actor_user_id?: string;
			/** Format: date-time */
			created_at: string;
			entity_id?: string;
			entity_type: string;
			/** Format: int64 */
			id: number;
			metadata: unknown;
		};
		CreateFolderInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/CreateFolderInputBody.json
			 */
			readonly $schema?: string;
			/** @description Trimmed on input. Must not be empty. */
			name: string;
		};
		CreateLinkInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/CreateLinkInputBody.json
			 */
			readonly $schema?: string;
			/** @description Defaults to true. */
			analytics_enabled?: boolean;
			/** @description Where the link points. https:// only. */
			destination_url: string;
			/** @description Optional. Defaults to the instance's shared domain. */
			domain_id?: string;
			/**
			 * Format: date-time
			 * @description Must be in the future.
			 */
			expires_at?: string;
			/** @description Optional. Must be a folder in this team. */
			folder_id?: string;
			/**
			 * Format: int64
			 * @description 301 is cached by browsers: clicks go uncounted and destination changes stop taking effect.
			 * @default 302
			 * @enum {integer}
			 */
			redirect_type: 301 | 302;
			/** @description Optional custom alias. Lowercased on input; generated when omitted. */
			slug?: string;
			/** @description Optional. Tags must belong to this team. */
			tag_ids?: string[] | null;
		};
		CreateTagInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/CreateTagInputBody.json
			 */
			readonly $schema?: string;
			/** @description Trimmed on input. Unique per team, case-insensitively. */
			name: string;
		};
		CreateTeamInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/CreateTeamInputBody.json
			 */
			readonly $schema?: string;
			/** @description The Verein's display name. */
			name: string;
		};
		ErrorDetail: {
			/** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
			location?: string;
			/** @description Error message text */
			message?: string;
			/** @description The value at the given location */
			value?: unknown;
		};
		ErrorModel: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/ErrorModel.json
			 */
			readonly $schema?: string;
			/**
			 * @description A human-readable explanation specific to this occurrence of the problem.
			 * @example Property foo is required but is missing.
			 */
			detail?: string;
			/** @description Optional list of individual error details */
			errors?: components['schemas']['ErrorDetail'][] | null;
			/**
			 * Format: uri
			 * @description A URI reference that identifies the specific occurrence of the problem.
			 * @example https://example.com/error-log/abc123
			 */
			instance?: string;
			/**
			 * Format: int64
			 * @description HTTP status code
			 * @example 400
			 */
			status?: number;
			/**
			 * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
			 * @example Bad Request
			 */
			title?: string;
			/**
			 * Format: uri
			 * @description A URI reference to human-readable documentation for the error.
			 * @default about:blank
			 * @example https://example.com/errors/example
			 */
			type: string;
		};
		Folder: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/Folder.json
			 */
			readonly $schema?: string;
			/** Format: date-time */
			created_at: string;
			id: string;
			name: string;
			team_id: string;
		};
		HealthOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/HealthOutputBody.json
			 */
			readonly $schema?: string;
			status: string;
		};
		Link: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/Link.json
			 */
			readonly $schema?: string;
			analytics_enabled: boolean;
			/** Format: date-time */
			created_at: string;
			created_by: string;
			destination_url: string;
			domain_id: string;
			/** Format: date-time */
			expires_at: string | null;
			folder_id: string;
			has_password: boolean;
			hostname: string;
			id: string;
			/** Format: int64 */
			redirect_type: number;
			short_url: string;
			slug: string;
			state: string;
			tags: components['schemas']['Tag'][] | null;
			team_id: string;
			/** Format: date-time */
			updated_at: string;
		};
		MeOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/MeOutputBody.json
			 */
			readonly $schema?: string;
			email: string;
			memberships: components['schemas']['TeamMembership'][] | null;
			user_id: string;
		};
		Member: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/Member.json
			 */
			readonly $schema?: string;
			/** Format: date-time */
			created_at: string;
			email: string;
			role: string;
			user_id: string;
		};
		PageAuditEntry: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PageAuditEntry.json
			 */
			readonly $schema?: string;
			items: components['schemas']['AuditEntry'][] | null;
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			per_page: number;
			/** Format: int64 */
			total_count: number;
		};
		PageFolder: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PageFolder.json
			 */
			readonly $schema?: string;
			items: components['schemas']['Folder'][] | null;
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			per_page: number;
			/** Format: int64 */
			total_count: number;
		};
		PageLink: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PageLink.json
			 */
			readonly $schema?: string;
			items: components['schemas']['Link'][] | null;
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			per_page: number;
			/** Format: int64 */
			total_count: number;
		};
		PageMember: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PageMember.json
			 */
			readonly $schema?: string;
			items: components['schemas']['Member'][] | null;
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			per_page: number;
			/** Format: int64 */
			total_count: number;
		};
		PageTag: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PageTag.json
			 */
			readonly $schema?: string;
			items: components['schemas']['Tag'][] | null;
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			per_page: number;
			/** Format: int64 */
			total_count: number;
		};
		PageTeam: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PageTeam.json
			 */
			readonly $schema?: string;
			items: components['schemas']['Team'][] | null;
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			per_page: number;
			/** Format: int64 */
			total_count: number;
		};
		Tag: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/Tag.json
			 */
			readonly $schema?: string;
			id: string;
			name: string;
			team_id: string;
		};
		Team: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/Team.json
			 */
			readonly $schema?: string;
			/** Format: date-time */
			created_at: string;
			id: string;
			name: string;
			role: string;
		};
		TeamMembership: {
			name: string;
			role: string;
			team_id: string;
		};
		UpdateFolderInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/UpdateFolderInputBody.json
			 */
			readonly $schema?: string;
			name: string;
		};
		UpdateLinkInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/UpdateLinkInputBody.json
			 */
			readonly $schema?: string;
			analytics_enabled?: boolean;
			destination_url?: string;
			/** Format: date-time */
			expires_at?: string;
			/** @description Send null to unfile the link. */
			folder_id?: string | null;
			/**
			 * Format: int64
			 * @enum {integer}
			 */
			redirect_type?: 301 | 302;
			slug?: string;
			/**
			 * @description expired follows from expires_at and flagged is set by scanning; neither is a caller's to write.
			 * @enum {string}
			 */
			state?: 'active' | 'disabled';
			/** @description Replaces the whole tag set. Send [] to remove every tag. */
			tag_ids?: string[] | null;
		};
		UpdateMemberInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/UpdateMemberInputBody.json
			 */
			readonly $schema?: string;
			/** @enum {string} */
			role: 'viewer' | 'editor' | 'admin' | 'owner';
		};
		UpdateTagInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/UpdateTagInputBody.json
			 */
			readonly $schema?: string;
			name: string;
		};
		UpdateTeamInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/UpdateTeamInputBody.json
			 */
			readonly $schema?: string;
			name: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	'delete-folder': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The folder this request operates on. */
				folder_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'update-folder': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The folder this request operates on. */
				folder_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateFolderInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Folder'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'get-health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'get-link': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The link this request operates on. */
				link_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Link'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'delete-link': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The link this request operates on. */
				link_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'update-link': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The link this request operates on. */
				link_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateLinkInputBody'];
				'application/octet-stream': string;
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Link'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'get-me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MeOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'delete-tag': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The tag this request operates on. */
				tag_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'update-tag': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The tag this request operates on. */
				tag_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateTagInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Tag'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'list-teams': {
		parameters: {
			query?: {
				/** @description 1-based page number. */
				page?: number;
				/** @description Items per page, capped at 100. */
				per_page?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PageTeam'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'create-team': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateTeamInputBody'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Team'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'get-team': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Team'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'update-team': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateTeamInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Team'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'list-audit-log': {
		parameters: {
			query?: {
				/** @description 1-based page number. */
				page?: number;
				/** @description Items per page, capped at 100. */
				per_page?: number;
				/** @description Restrict to one entity type. */
				entity_type?: 'team' | 'team_member' | 'domain' | 'folder' | 'tag' | 'link';
				/** @description Restrict to one action, e.g. team_member.removed. */
				action?: string;
				/** @description Restrict to one actor, as a UUID. */
				actor_user_id?: string;
				/** @description Only entries at or after this instant (RFC 3339). */
				from?: string;
				/** @description Only entries at or before this instant (RFC 3339). */
				to?: string;
			};
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PageAuditEntry'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'list-folders': {
		parameters: {
			query?: {
				/** @description 1-based page number. */
				page?: number;
				/** @description Items per page, capped at 100. */
				per_page?: number;
			};
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PageFolder'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'create-folder': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateFolderInputBody'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Folder'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'list-links': {
		parameters: {
			query?: {
				/** @description 1-based page number. */
				page?: number;
				/** @description Items per page, capped at 100. */
				per_page?: number;
				/** @description Substring match across the slug and the destination URL. */
				q?: string;
				/** @description Restrict to one state. */
				state?: 'active' | 'disabled' | 'expired' | 'flagged';
				/** @description Restrict to one domain, as a UUID. */
				domain_id?: string;
				/** @description Restrict to one folder, as a UUID. */
				folder_id?: string;
				/** @description Restrict to links carrying one tag, as a UUID. */
				tag_id?: string;
				/** @description Newest first by default. */
				sort?: 'created_at' | '-created_at';
			};
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PageLink'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'create-link': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateLinkInputBody'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Link'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'list-team-members': {
		parameters: {
			query?: {
				/** @description 1-based page number. */
				page?: number;
				/** @description Items per page, capped at 100. */
				per_page?: number;
			};
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PageMember'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'add-team-member': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddMemberInputBody'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Member'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'remove-team-member': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
				/** @description The member to remove. */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'update-team-member': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
				/** @description The member to change. */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateMemberInputBody'];
			};
		};
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'list-tags': {
		parameters: {
			query?: {
				/** @description 1-based page number. */
				page?: number;
				/** @description Items per page, capped at 100. */
				per_page?: number;
			};
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PageTag'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
	'create-tag': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description The team this request operates on. */
				team_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateTagInputBody'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Tag'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/problem+json': components['schemas']['ErrorModel'];
				};
			};
		};
	};
}
